export TXT_FILE_PATH="/home/francisco/GitProyects/INFO198_SO/Data/Users.txt"
export MAPA_ARCHIVOS="/home/francisco/GitProyects/INFO198_SO/Data"
export STOP_WORDS="/home/francisco/GitProyects/INFO198_SO/Data/stop_words.txt"
export INVERTED_INDEX="/home/francisco/GitProyects/INFO198_SO/Data/index.INDEX"
export CANTIDAD_THREAD="3"
export RESULTADOS="/home/francisco/GitProyects/INFO198_SO/Data/resultados.txt"
export PROCESOS="/home/francisco/GitProyects/INFO198_SO/Data/procesos.txt"
export SOCKET_DIR="/home/francisco/GitProyects/INFO198_SO/sockets"
export COUNTWORDS_OUT="./app2"
export COUNTWORD_THREADS_OUT="./app3 default"
export PLANIFICADOR_OUT="./planificador"
export INVERTED_OUT="./app4"
export CANTIDAD_CORES="3"
export CARPETA_ENTRADA="/home/francisco/GitProyects/INFO198_SO/in/libros"
export CARPETA_SALIDA="/home/francisco/GitProyects/INFO198_SO/out"
export REPETICIONES="5"
export DATOS="/home/francisco/GitProyects/INFO198_SO/src/ContarPalabras/AnalisisPerformance/variablesEntorno/DATOS.txt"
export GRAPH_PYTHON_PATH="/home/francisco/GitProyects/INFO198_SO/src/ContarPalabras/AnalisisPerformance/ANALIZADOR.py"
export GRAFICO="/home/francisco/GitProyects/INFO198_SO/Data"
export ARRAY_THREADS="1,2,4,8,16"
export COUNT_WITH_THREADS="./app3 -h " #nueo
export PERFORMANCE_OUT="./app5"
export MEMORY_SIZE="30"
export TOPK = "5"

# export CARPETA_ENTRADA="/home/vicntea/INFO198_SO/in/libros"
# export CARPETA_SALIDA="/home/vicntea/INFO198_SO/out"

# export CANTIDAD_THREAD="3"
# export GRAFICO="/home/vicntea/INFO198_SO/Data/grafico.png"
# export REPETICIONES="3"
# export GRAPH_DATA="/home/vicntea/INFO198_SO/src/ContarPalabras/AnalisisPerformance/variablesEntorno\DATOS.txt"
# export GRAPH_PYTHON_PATH="/home/vicntea/INFO198_SO/src/ContarPalabras/AnalisisPerformance/ANALIZADOR.py"

# export TXT_FILE_PATH="/home/vicntea/INFO198_SO/Data/Users.txt"
# export MAPA_ARCHIVOS="/home/vicntea/INFO198_SO/Data"
# export STOP_WORDS="/home/vicntea/INFO198_SO/Data/stop_words.txt"
# export INVERTED_INDEX="/home/vicntea/INFO198_SO/Data/index.INDEX"
# export RESULTADOS="/home/vicntea/INFO198_SO/Data/resultados.txt"
# export PROCESOS="/home/vicntea/INFO198_SO/Data/procesos.txt"
# export SOCKET_DIR="/home/vicntea/INFO198_SO/sockets"
# export COUNTWORDS_OUT="./app2"
# export COUNTWORD_THREADS_OUT="./app3 default"
# export COUNT_WITH_THREADS="./app3 -h " #nueo
# export PLANIFICADOR_OUT="./planificador"
# export INVERTED_OUT="./app4"
# export CANTIDAD_CORES="3"
# export PERFORMANCE_OUT="./app5"

# export CARPETA_ENTRADA="/home/vicntea/INFO198_SO/in/libros"
# export CARPETA_SALIDA="/home/vicntea/INFO198_SO/out"

# export CANTIDAD_THREAD="3"
# export ARRAY_THREADS="1,2,4,8,16"
# export GRAFICO="/home/vicntea/INFO198_SO/Data/grafico.png"
# export REPETICIONES="5"
# export GRAPH_DATA="/home/vicntea/INFO198_SO/src/ContarPalabras/AnalisisPerformance/variablesEntorno\DATOS.txt"
# export GRAPH_PYTHON_PATH="/home/vicntea/INFO198_SO/src/ContarPalabras/AnalisisPerformance/ANALIZADOR.py"

# export MEMORY_SIZE="30"
# export TOPK = "5"
